config/routes.rb
TestProject::Application.routes.draw do

  get "quizzes/index"

  get "quizzes/new"

  get "quizzes/edit"

  root              :to => 'quizzes#index'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match 'signup',   :to => 'users#new'

  get "users/new"

end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id            :integer          not null, primary key
#  test_id       :integer
#  text          :string(45)
#  type_question :integer          default(0), not null
#  created_at    :datetime
#  updated_at    :datetime
#

class Question < ActiveRecord::Base

	belongs_to :test, :class_name => "Quiz"

	attr_accessible :id, :test_id, :text, :type_question

	validates :text, :presence => true, :length => { :maximum => 340 }
    validates :test_id, :presence => true

	default_scope :order => 'questions.id DESC'
end

app/models/quiz.rb
# == Schema Information
#
# Table name: tests
#
#  id         :integer          not null, primary key
#  title      :string(45)
#  time       :time
#  status     :integer
#  created_at :datetime
#  updated_at :string(45)
#

class Quiz < ActiveRecord::Base
	set_table_name "tests"
	attr_accessible :tilte, :time, :status, :test_id
	has_many :questions, :foreign_key => "test_id",:dependent => :destroy
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id           :integer          not null, primary key
#  email        :string(45)
#  display_name :string(45)
#  skype        :string(45)
#  country      :string(45)
#  password     :string(45)
#  salt         :string(45)
#  created_at   :datetime
#  updated_at   :datetime
#

class User < ActiveRecord::Base
	attr_accessible :name, :email, :display_name, :skype , :country, :password, :salt
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end

  def help
    @title = "Help"
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  def index
  	@tests = Quiz.all
  	@title = "Tests"
    Time::DATE_FORMATS[:limit] = "%M"
  end

  def show
  	@test = Quiz.find(params[:id])
  	@title = @test.title
  end

  def new
  end

  def edit
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @title = "Sign up"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Return a title on a per-page basis.
  def title
    base_title = "Ruby on Rails Tutorial Sample App"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end

  def logo
   	logo = image_tag("logo.png", :alt => "Sample App", :class => "round")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "Help", help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Tests", root_path %></li>
      <li><%= link_to "Sign in", '#' %></li>
      <li><%= link_to "Sign up", '#' %></li>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
<h1>Pages#help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/home.html.erb
<h1>Sample App</h1>

<p>
  This is the home page for the
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>

<%= link_to "Sign up now!", signup_path, :class => "button round" %>

app/views/quizzes/_quiz.html.erb
<li>
  <%= tests %>
</li>

app/views/quizzes/edit.html.erb
<h1>Quiz#edit</h1>
<p>Find me in app/views/quiz/edit.html.erb</p>

app/views/quizzes/index.html.erb
<h1>Tests</h1>
<table>
<% @tests.each do |test| %>
    <tr>
      <td>
        <%= test.title %> ( <%= test.questions.count %> questions 
        for <%= test.time.to_s(:limit) %> minutes)
      </td>
      <td>
 		<%= link_to "Edit", '#' %>  
 	  </td> 
 	  <td>
    	<%= link_to "Delete", '#' %>
      </td>
    </tr> 
  <% end %>
</table>
<%= link_to "Create test", '#',:class => "button round" %>

app/views/quizzes/new.html.erb
<h1>Quiz#new</h1>
<p>Find me in app/views/quiz/new.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>